### ISSUE TITLE
Permission For Use

### ISSUE THREAD

**Issue by zerox1212** [zeroentity/opcua-2-azure#1]
@oroulet,

I know freeopcua client is LGPL, but I just want to make sure it's OK for me to turn your sample client into an OPC UA to Azure bridge tool. Your client has a lot of the things I would need for this tool so it's faster to start with what you already created.

Is it OK for me to use it this way?

Thanks,
Andrew

**Comment by oroulet** [comment]
This is perfectly fine. Lgpl is really permissive

**Comment by zerox1212** [comment]
Thanks.
